changesetBaseRefs:
  - main

nodeLinker: pnp

packageExtensions:
  "@babel/plugin-proposal-decorators@*":
    dependencies:
      "@babel/core": "*"
  "@babel/plugin-syntax-dynamic-import@*":
    dependencies:
      "@babel/core": "*"
  "@babel/plugin-transform-react-jsx@*":
    dependencies:
      "@babel/core": "*"
  "@babel/plugin-transform-runtime@*":
    dependencies:
      "@babel/core": "*"
  "@babel/preset-env@*":
    dependencies:
      "@babel/core": "*"
  "@babel/preset-react@*":
    dependencies:
      "@babel/core": "*"
  "@mdx-js/react@*":
    dependencies:
      react: "*"
  "@parcel/cache@*":
    dependencies:
      "@parcel/core": "*"
  "@parcel/fs@*":
    dependencies:
      "@parcel/core": "*"
  "@parcel/package-manager@*":
    dependencies:
      "@parcel/core": "*"
  "@parcel/workers@*":
    dependencies:
      "@parcel/core": "*"
  "@storybook/addon-essentials@*":
    dependencies:
      babel-loader: "*"
  "@storybook/addon-measure@*":
    dependencies:
      "@storybook/components": "*"
      "@storybook/core-events": "*"
      "@storybook/theming": "*"
  "@storybook/core-client@*":
    dependencies:
      webpack: "*"
  babel-loader@*:
    dependencies:
      webpack: "*"
  eslint-config-airbnb-base@*:
    dependencies:
      eslint: "*"
      eslint-plugin-import: "*"
  fork-ts-checker-webpack-plugin@*:
    dependencies:
      typescript: "*"
      webpack: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-berry.cjs
